### ISSUE TITLE
Empty path masks field causes issues

### ISSUE THREAD

**Issue by BrenekH** [BrenekH/encodarr#111]
When the path masks field is left empty, it matches against every file.

**Comment by BrenekH** [comment]
This has been released in [0.3.1](https://github.com/BrenekH/encodarr/releases/0.3.1).

**Comment by tr1p0p** [comment]
Seem the last released don't fix the issues for me, still have empty queue when i have path mask field empty. On a fresh install on a fresh server (Debian 10 arm64)

**Comment by BrenekH** [comment]
Since this was a client-side fix (in the WebUI), could you see if ignoring the cache while reloading (Ctrl + F5 on most browsers) fixes the issue. You will have to edit the library and then save it again.

Also, in the About section on the Settings page, does the Controller version say 0.3.1? I did have an issue when updating myself that I had to change the docker tag to 0.3.1 to get the right version.

**Comment by tr1p0p** [comment]
i didn't use docker just download arm64 build on release page. I try but don't seem to make a change, will see the logs. And yeah controller settings show 0.3.1

**Comment by BrenekH** [comment]
Did it fix itself or are the logs still saying skipped?

**Comment by tr1p0p** [comment]
the logs still show the same error..

**Comment by tr1p0p** [comment]
I think you should re-open this issues to saw what's wrong.

**Comment by tr1p0p** [comment]
Still have this also when add a thing into path mask : https://github.com/BrenekH/encodarr/issues/112

So yeah, 0.3.1 don't solve anything to me.

**Comment by BrenekH** [comment]
Fixes for #111 and #112 have been merged into develop. Can you check to make sure [the binaries](https://github.com/BrenekH/encodarr/actions/runs/1264264375) fix your issue before I release it?

**Comment by tr1p0p** [comment]
Still having SQL issues..

**Comment by BrenekH** [comment]
Really? Even with a new database? The old one isn't going to work. 

If it's still an issue with a new db, can you post the full error logs in #112.
