### ISSUE TITLE
Can't create config folder at first launch, even with all permission

### ISSUE THREAD

**Issue by tr1p0p** [BrenekH/encodarr#93]
For some reason, encodarr-controller can't launch without "`sudo`" before, because it can't create a folder into .config for.. whatever reason. Trying everything :

```
admin@nullmoon:~/Encodarr $ ls -l encodarr-controller
-rwxr--r-- 1 admin 1007 16457113 Apr 23 23:48 encodarr-controller
admin@nullmoon:~/Encodarr $ ./encodarr-controller
mkdir /home/admin/.config/encodarr/controller/config: permission denied
admin@nullmoon:~/Encodarr $ chmod 777 encodarr-controller
admin@nullmoon:~/Encodarr $ ./encodarr-controller
mkdir /home/admin/.config/encodarr/controller/config: permission denied
admin@nullmoon:~/Encodarr $ sudo chmod 777 encodarr-controller
admin@nullmoon:~/Encodarr $ ./encodarr-controller
mkdir /home/admin/.config/encodarr/controller/config: permission denied
```

Running on Debian 10 with RPI 4 on arm64

**Comment by BrenekH** [comment]
So I've figured out what was wrong, basically Encodarr didn't take into consideration the umask, which caused it to make `~/.config/encodarr` not-writable. Fix should be coming out as 0.2.1 in the next hour or so. I'll close this when it's ready.

**Comment by BrenekH** [comment]
Alright, the fix is now available.

[https://github.com/BrenekH/encodarr/releases/tag/0.2.1](https://github.com/BrenekH/encodarr/releases/tag/0.2.1)

**Comment by tr1p0p** [comment]
Thks ! I confirm it's working now
